In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_columns',None)

In [2]:
train_data=pd.read_csv('Train.csv')

In [3]:
train_data.shape

(1763, 1559)

In [4]:
train_data.head()

feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  \
0        100        160     1.6000          0          0          0   
1         20         83     4.1500          1          0          0   
2         99        150     1.5151          1          0          0   
3         40         40     1.0000          0          0          0   
4         12        234    19.5000          1          0          0   

   feature_7  feature_8  feature_9  feature_10  feature_11  feature_12  \
0          0          0          0           0           0           0   
1          0          0          0           1           0           0   
2          0          0          0           0           0           0   
3          0          0          0           0           0           0   
4          0          0          0           0           0           0   

   feature_13  feature_14  feature_15  feature_16  feature_17  feature_18  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   feature_19  feature_20  feature_21  feature_22  feature_23  feature_24  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           1           0           0           0           0   
4           0           0           0           0           0           0   

   feature_25  feature_26  feature_27  feature_28  feature_29  feature_30  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   feature_31  feature_32  feature_33  feature_34  feature_35  feature_36  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   feature_37  feature_38  feature_39  feature_40  feature_41  feature_42  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   feature_43  feature_44  feature_45  feature_46  feature_47  feature_48  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           1   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   feature_49  feature_50  feature_51  feature_52  feature_53  feature_54  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0        

In [5]:
train_data['Class'].value_counts()

0    1620
1     143
Name: Class, dtype: int64

In [6]:
X=train_data.iloc[:,:-1]
y=train_data.iloc[:,-1]
X.shape,y.shape

((1763, 1558), (1763,))

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [8]:
#Handling Imbalance Dataset using CROSS VALIDATION AND K FOLD

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [10]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,shuffle=False,random_state=None)

In [11]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\Users\welcome\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [12]:
y_pred=clf.predict(X_test)

In [13]:
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_pred))
print("\n")
print(classification_report(y_test,y_pred))

Confusion Matrix:
[[469  17]
 [ 27  16]]


accuracy Score:
0.9168241965973535


              precision    recall  f1-score   support

           0       0.95      0.97      0.96       486
           1       0.48      0.37      0.42        43

    accuracy                           0.92       529
   macro avg       0.72      0.67      0.69       529
weighted avg       0.91      0.92      0.91       529



In [14]:
class_weight=dict({0:1,1:100}) #GIVING MORE IMPORTANCE TO 1 

In [15]:
from sklearn.ensemble import RandomForestClassifier
clasf=RandomForestClassifier(class_weight=class_weight)
clasf.fit(X_train,y_train)
clasf.score(X_train,y_train)

0.9967585089141004

In [17]:
y_predd=clasf.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_predd))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_predd))
print("\n")
print(classification_report(y_test,y_predd))

Confusion Matrix:
[[467  19]
 [ 25  18]]


accuracy Score:
0.9168241965973535


              precision    recall  f1-score   support

           0       0.95      0.96      0.96       486
           1       0.49      0.42      0.45        43

    accuracy                           0.92       529
   macro avg       0.72      0.69      0.70       529
weighted avg       0.91      0.92      0.91       529



In [18]:
#UnderSampling


In [19]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.6) #Reducing Points by 80%
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))

C:\Users\welcome\anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.6 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of classes before fit Counter({0: 1134, 1: 100})
the number of classes after fit Counter({0: 166, 1: 100})


In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [29]:
classifier.score(X_train_ns,y_train_ns)

0.9887218045112782

In [30]:
y_prd=classifier.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_prd))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_prd))
print("\n")
print(classification_report(y_test,y_prd))

Confusion Matrix:
[[128 358]
 [ 10  33]]


accuracy Score:
0.30434782608695654


              precision    recall  f1-score   support

           0       0.93      0.26      0.41       486
           1       0.08      0.77      0.15        43

    accuracy                           0.30       529
   macro avg       0.51      0.52      0.28       529
weighted avg       0.86      0.30      0.39       529



In [23]:
#Over Sampling

In [24]:
from imblearn.over_sampling import RandomOverSampler

In [48]:
os=RandomOverSampler(0.95)
X_train_os,y_train_os=os.fit_sample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_os)))


C:\Users\welcome\anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.95 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of classes before fit Counter({0: 1134, 1: 100})
the number of classes after fit Counter({0: 1134, 1: 1077})


In [49]:
from sklearn.ensemble import RandomForestClassifier
clas=RandomForestClassifier()
clas.fit(X_train_os,y_train_os)                           

RandomForestClassifier()

In [50]:
clas.score(X_train_os,y_train_os)

0.9981908638625057

In [51]:
y_predd=clas.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_predd))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_predd))
print("\n")
print(classification_report(y_test,y_predd))

Confusion Matrix:
[[462  24]
 [ 22  21]]


accuracy Score:
0.9130434782608695


              precision    recall  f1-score   support

           0       0.95      0.95      0.95       486
           1       0.47      0.49      0.48        43

    accuracy                           0.91       529
   macro avg       0.71      0.72      0.71       529
weighted avg       0.91      0.91      0.91       529



In [38]:
#SMOTE technique
from imblearn.combine import SMOTETomek

In [40]:
sm=SMOTETomek(0.80)
X_train_sm,y_train_sm=sm.fit_sample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_sm)))

C:\Users\welcome\anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of classes before fit Counter({0: 1134, 1: 100})
the number of classes after fit Counter({0: 1127, 1: 900})


In [41]:
from sklearn.ensemble import RandomForestClassifier
cla=RandomForestClassifier()
cla.fit(X_train_sm,y_train_sm)                           

RandomForestClassifier()

In [42]:
cla.score(X_train_sm,y_train_sm)

0.9955599407992106

In [43]:
y_pred=cla.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_pred))
print("\n")
print(classification_report(y_test,y_pred))

Confusion Matrix:
[[421  65]
 [ 19  24]]


accuracy Score:
0.8412098298676749


              precision    recall  f1-score   support

           0       0.96      0.87      0.91       486
           1       0.27      0.56      0.36        43

    accuracy                           0.84       529
   macro avg       0.61      0.71      0.64       529
weighted avg       0.90      0.84      0.86       529



In [10]:
# #FiLTER METHODS FOR FEATURE SELECTION
# Features selected using filter methods can be used as an input to any machine learning models.

# Univariate -> Fisher Score, Mutual Information Gain, Variance etc
# Multi-variate -> Pearson Correlation

In [11]:
# #The univariate filter methods are the type of methods where individual features are ranked according to specific criteria. 
# The top N features are then selected. Different types of ranking criteria are used for univariate filtermethods, for example 
# fisher score, mutual information, and variance of the feature.

In [12]:
# Multivariate filter methods are capable of removing redundant features from the 
# data since they take the mutual relationship between the features into account.

In [13]:
#Univariate MEthods

In [52]:
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import VarianceThreshold

In [53]:
constant_filter = VarianceThreshold(threshold=0)
constant_filter.fit(X_train)

VarianceThreshold(threshold=0)

In [54]:
constant_filter.get_support().sum() #No of features left after Removing COnstant Features

1505

In [55]:
X_train_filter = constant_filter.transform(X_train)
X_test_filter = constant_filter.transform(X_test)

In [56]:
X_train_filter.shape, X_test_filter.shape, X_train.shape

((1234, 1505), (529, 1505), (1234, 1558))

In [57]:
quasi_constant_filter = VarianceThreshold(threshold=0.01)
quasi_constant_filter.fit(X_train_filter)
VarianceThreshold(threshold=0.01)

VarianceThreshold(threshold=0.01)

In [58]:
quasi_constant_filter.get_support().sum()

229

In [59]:
X_train_quasi_filter = quasi_constant_filter.transform(X_train_filter)
X_test_quasi_filter = quasi_constant_filter.transform(X_test_filter)
X_train_quasi_filter.shape, X_test_quasi_filter.shape

((1234, 229), (529, 229))

In [60]:
X_train_T = X_train_quasi_filter.T
X_test_T = X_test_quasi_filter.T
type(X_train_T)


numpy.ndarray

In [61]:
X_train_T = pd.DataFrame(X_train_T)
X_test_T = pd.DataFrame(X_test_T)

In [62]:
X_train_T.duplicated().sum()

66

In [63]:
duplicated_features = X_train_T.duplicated()
duplicated_features

0      False
1      False
2      False
3      False
4      False
       ...  
224    False
225    False
226    False
227     True
228     True
Length: 229, dtype: bool

In [64]:
features_to_keep = [not index for index in duplicated_features]

In [65]:
X_train_unique = X_train_T[features_to_keep].T
X_test_unique = X_test_T[features_to_keep].T

In [66]:
X_train_unique.shape, X_train.shape

((1234, 163), (1234, 1558))

In [67]:
from sklearn.ensemble import RandomForestClassifier
clf2=RandomForestClassifier(class_weight=class_weight)
clf2.fit(X_train_unique,y_train)
clf2.score(X_train_unique,y_train)

0.9724473257698542

In [69]:
y_prd=clf2.predict(X_test_unique)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_prd))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_prd))
print("\n")
print(classification_report(y_test,y_prd))

Confusion Matrix:
[[454  32]
 [ 26  17]]


accuracy Score:
0.8903591682419659


              precision    recall  f1-score   support

           0       0.95      0.93      0.94       486
           1       0.35      0.40      0.37        43

    accuracy                           0.89       529
   macro avg       0.65      0.66      0.65       529
weighted avg       0.90      0.89      0.89       529



In [70]:
os=RandomOverSampler(0.95)
X_train_os1,y_train_os1=os.fit_sample(X_train_unique,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_os1)))


the number of classes before fit Counter({0: 1134, 1: 100})
the number of classes after fit Counter({0: 1134, 1: 1077})


C:\Users\welcome\anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.95 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


In [71]:
from sklearn.ensemble import RandomForestClassifier
clf3=RandomForestClassifier()
clf3.fit(X_train_os1,y_train_os1)
clf3.score(X_train_os1,y_train_os1)

0.9873360470375395

In [72]:
y_prd=clf3.predict(X_test_unique)
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_prd))
print("\n")
print("accuracy Score:")
print(accuracy_score(y_test,y_prd))
print("\n")
print(classification_report(y_test,y_prd))

Confusion Matrix:
[[463  23]
 [ 22  21]]


accuracy Score:
0.9149338374291115


              precision    recall  f1-score   support

           0       0.95      0.95      0.95       486
           1       0.48      0.49      0.48        43

    accuracy                           0.91       529
   macro avg       0.72      0.72      0.72       529
weighted avg       0.92      0.91      0.92       529

